exports.name = "";
exports.type = "";
exports.pos_x = 0;
exports.pos_y = 0;
exports.target_x = 0;
exports.target_y = 0;
exports.move_speed = 1;
exports.aggressive = true;
exports.view_range = 100;
exports.in_combat = false;
exports.health = 100;
exports.sprite = "sprite";
exports.alive = true;
exports.target_entity = "";
exports.origin_x = 0;
exports.origin_y = 0;
exports.roam_range = 100;

module.exports = function () {};